spring:
    application:
        name: 'notification-service'
    cloud:
        discovery:
            enabled: false

jwt:
    secret: qwerty

notificationService:
    registerStompEndpoint: '/stomp'
    allowedOrigins: http://127.0.0.1:8081
    tokenValiditySeconds: 3153600000 # 100 years