spring:
    application:
        name: 'booking-service'
    cloud:
        discovery:
            enabled: false
    datasource:
        url: jdbc:h2:mem:testdb
        username: root
        password:
        driver-class-name: org.h2.Driver
        schema: classpath:/db_scripts/h2/booking_service_schema_h2.sql
        data: classpath:/db_scripts/h2/booking_service_demo_h2.sql
    jpa:
        database-platform: org.hibernate.spatial.dialect.h2geodb.GeoDBDialect
        hibernate:
            ddl-auto:
                update
    h2:
        console:
            enabled:
                true
