spring:
    cloud:
        discovery:
            enabled: true
    datasource:
        url: "jdbc:postgresql://booking-service-database:5432/booking_service"
        username: "postgres"
        password: "qwerty"
        initialization-mode: never
        driverClassName: org.postgresql.Driver
        schema:
        data:
    jpa:
        database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
        hibernate:
            ddl-auto: none

logging:
    level:
        org:
            springframework: DEBUG

eureka:
    client:
        serviceUrl:
            defaultZone: 'http://eureka-naming-server:8761/eureka/'