spring:
    application:
        name: 'booking-service'
    cloud:
        discovery:
            enabled: false
    datasource:
        url: jdbc:mysql://localhost:${mariaDB4j.port}/test
        username: root
        password:
        driver-class-name: org.mariadb.jdbc.Driver
        schema: classpath:/db_scripts/h2/booking_service_schema_h2.sql
        data: classpath:/db_scripts/h2/booking_service_demo_h2.sql
    jpa:
        database-platform: org.hibernate.spatial.dialect.mysql.MySQL56SpatialDialect
        hibernate:
            ddl-auto:
                update

mariaDB4j:
    dataDir:
    port: 3307
