spring:
    cloud:
        discovery:
            enabled: true
    # datasource:
    #     url: '${SPRING_DATASOURCE_URL}'
    #     username: '${SPRING_DATASOURCE_USERNAME}'
    #     password: '${SPRING_DATASOURCE_PASSWORD}'
    #     initialization-mode: never
    # jpa:
    #     hibernate:
    #         ddl-auto: none

# logging:
#     level:
#         org:
#             springframework: DEBUG

eureka:
    client:
        serviceUrl:
            defaultZone: 'http://eureka-naming-server:8761/eureka/'