swagger: "2.0"
info:
    description: "Service for handling commerce operations"
    version: "1.0.0"
    title: "Commerce service"
host: "commerce-service.taxi-microservice.com"
basePath: "/"
schemes:
    - "https"
    - "http"
tags:
    - name: "commerce"
      description: "Commerce operations"
paths:
    /salary/driver/{driverId}:
        get:
            parameters:
                -   in: "path"
                    type: "string"
                    name: "driverId"
                    required: true
            responses:
                "200":
                    description: ""
    /generate-report:
        get:
            responses:
                "200":
                    description: ""
