spring:
    application:
        name: 'user-service'
    cloud:
        discovery:
            enabled: false
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: h2
        password: qwerty
        schema: classpath:/db_scripts/h2/user_service_schema_h2.sql
        data: classpath:/db_scripts/h2/user_service_demo_h2.sql
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto:
                update
    h2:
        console:
            enabled:
                true

userService:
    kafka:
        bootstrapAddress: "localhost:9092"
        groupId: "passenger_service_group"
        topics:
            addPassengerTopic: "add_passenger_topic"
            addPassengerReplyTopic: "add_passenger_reply_topic"
            getPassengersPageTopic: "get_passengers_page_topic"
            getPassengersPageReplyTopic: "get_passengers_page_reply_topic"
            addDriverTopic: "add_driver_topic"
            addDriverReplyTopic: "add_driver_reply_topic"
            getDriversPageTopic: "get_drivers_page_topic"
            getDriversPageReplyTopic: "get_drivers_page_reply_topic"
