@startuml

hide footbox

actor Passenger
participant "BookingService" as BookingService  << (S,#ADD1B2) Server >>
participant "NotificationService" as NotificationService  << (S,#ADD1B2) Server >>

Passenger -> BookingService : assignDriver

alt status is CREATED

    BookingService -> BookingService : assignDriverToOrder

    BookingService -> NotificationService : sendNotificationToDriver

    BookingService -> NotificationService : sendNotificationToPassenger

else status is not CREATED

    BookingService -> NotificationService : displayErrorMessage

end

@enduml