@startuml

hide footbox

actor Passenger
participant "BookingService" as BookingService  << (S,#ADD1B2) Server >>
participant "NotificationService" as NotificationService  << (S,#ADD1B2) Server >>

Passenger -> BookingService : changeDriver

alt status is CREATED or ASSIGNED

    BookingService -> BookingService : setNewDriver

    BookingService -> NotificationService : sendNotificationToDriver

    BookingService -> NotificationService : sendNotificationToPassenger

else status is not CREATED and not in ASSIGNED

    BookingService -> NotificationService : displayErrorMessage

end

@enduml