spring:
    application:
        name: 'passenger-service'
        exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
    cloud:
        discovery:
            enabled: false

passengerService:
    kafka:
        bootstrapAddress: "localhost:9092"
        groupId: "passenger_service_group"
        topics:
            addPassengerTopic: "add_passenger_topic"
            addPassengerReplyTopic: "add_passenger_reply_topic"