# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: eskatos/gradle-command-action@v1
        name: build user-service
        with:
          wrapper-directory: user-service
          build-root-directory: user-service
          gradle-version: 6.5.1
          arguments: build
      - name: publish user-service test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: unit-tests-results
          if-no-files-found: error
          path:  |
            user-service/build/reports/tests/test
            
      - uses: eskatos/gradle-command-action@v1
        name: build passenger-service
        with:
          wrapper-directory: passenger-service
          build-root-directory: passenger-service
          gradle-version: 6.5.1
          arguments: build
      - name: publish passenger-service test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: unit-tests-results
          if-no-files-found: error
          path:  |
            passenger-service/build/reports/tests/test
      
