# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Unit test workflow

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: eskatos/gradle-command-action@v1
        name: build user-service
        with:
          wrapper-directory: user-service
          build-root-directory: user-service
          gradle-version: 6.5.1
          arguments: build
      - name: publish user-service unit test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: user-service-unit-tests-results
          if-no-files-found: error
          path:  |
            user-service/build/reports/tests/test
            
      - uses: eskatos/gradle-command-action@v1
        name: build passenger-service
        with:
          wrapper-directory: passenger-service
          build-root-directory: passenger-service
          gradle-version: 6.5.1
          arguments: build
      - name: publish passenger-service unit test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: passenger-service-unit-tests-results
          if-no-files-found: error
          path:  |
            passenger-service/build/reports/tests/test

      - uses: eskatos/gradle-command-action@v1
        name: build driver-service
        with:
          wrapper-directory: driver-service
          build-root-directory: driver-service
          gradle-version: 6.5.1
          arguments: build
      - name: publish driver-service unit test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: driver-service-unit-tests-results
          if-no-files-found: error
          path:  |
            driver-service/build/reports/tests/test

      - uses: eskatos/gradle-command-action@v1
        name: build booking-service
        with:
          wrapper-directory: booking-service
          build-root-directory: booking-service
          gradle-version: 6.5.1
          arguments: build
      - name: publish booking-service unit test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: booking-service-unit-tests-results
          if-no-files-found: error
          path:  |
            booking-service/build/reports/tests/test

      - uses: eskatos/gradle-command-action@v1
        name: build notification-service
        with:
          wrapper-directory: notification-service
          build-root-directory: notification-service
          gradle-version: 6.5.1
          arguments: build
      - name: publish notification-service unit test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: notification-service-unit-tests-results
          if-no-files-found: error
          path:  |
            notification-service/build/reports/tests/test
      
